[package]
name = "my-offchain"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1"
serde = {version = "1", features = ["derive"]}

[dev-dependencies]
assert_cmd = "2.0.4"
predicates = "2.1.1"
